
package RestaurantManagementSystem;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.text.JEditorPane;
import javax.swing.text.JTextPane;
import javax.swing.text.EditorKit;

/**
 *
 * @author Mohit
 */
public class RestaurantManagementSystem extends javax.swing.JFrame {

    double[] foodItem = new double[7];
    double[] cafeItem = new double[7];
    double[] f = new double[7];
    double[] c = new double[7];

    /**
     * Creates new form RestaurantManaementSystem
     */
    public RestaurantManagementSystem() {
        //this.foodItem = new double[foodItem.length];
        //this.cafeItem=new double[cafeItem.length];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBoxChickenMoMo = new javax.swing.JCheckBox();
        jCheckBoxChowmin = new javax.swing.JCheckBox();
        jCheckBoxBurger = new javax.swing.JCheckBox();
        jCheckBoxPizza = new javax.swing.JCheckBox();
        jCheckBoxFrenchFries = new javax.swing.JCheckBox();
        jCheckBoxChickenChilli = new javax.swing.JCheckBox();
        jCheckBoxChickenWings = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldMoMo = new javax.swing.JTextField();
        jTextFieldBurger = new javax.swing.JTextField();
        jTextFieldChowmin = new javax.swing.JTextField();
        jTextFieldPizza = new javax.swing.JTextField();
        jTextFieldFries = new javax.swing.JTextField();
        jTextFieldChilli = new javax.swing.JTextField();
        jTextFieldWings = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxColdDrinks = new javax.swing.JCheckBox();
        jCheckBoxIcedCappuccino = new javax.swing.JCheckBox();
        jCheckBoxBlackForest = new javax.swing.JCheckBox();
        jCheckBoxBlueberry = new javax.swing.JCheckBox();
        jCheckBoxCreamedPie = new javax.swing.JCheckBox();
        jCheckBoxWaterMelon = new javax.swing.JCheckBox();
        jCheckBoxDickyDan = new javax.swing.JCheckBox();
        jTextFieldColdDrinks = new javax.swing.JTextField();
        jTextFieldIcedCappuccino = new javax.swing.JTextField();
        jTextFieldBlackForest = new javax.swing.JTextField();
        jTextFieldBlueberry = new javax.swing.JTextField();
        jTextFieldCreamedPie = new javax.swing.JTextField();
        jTextFieldWaterMelon = new javax.swing.JTextField();
        jTextFieldDickyDan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceipt = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFoodTax = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldSubTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCostOfFoodItem = new javax.swing.JTextField();
        jTextFieldCostOfCafeItem = new javax.swing.JTextField();
        jTextFieldServiceCharge = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButtonTotal = new javax.swing.JButton();
        jButtonReceipt = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRandomId = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jCheckBoxChickenMoMo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxChickenMoMo.setText("Chicken Mo:Mo");
        jCheckBoxChickenMoMo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxChickenMoMoMouseClicked(evt);
            }
        });
        jCheckBoxChickenMoMo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChickenMoMoActionPerformed(evt);
            }
        });

        jCheckBoxChowmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxChowmin.setText("Chicken Chowmin");
        jCheckBoxChowmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxChowminMouseClicked(evt);
            }
        });
        jCheckBoxChowmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxChowminActionPerformed(evt);
            }
        });

        jCheckBoxBurger.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxBurger.setText("Chicken Burger");
        jCheckBoxBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBurgerMouseClicked(evt);
            }
        });
        jCheckBoxBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBurgerActionPerformed(evt);
            }
        });

        jCheckBoxPizza.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxPizza.setText("Chicken Pizza");
        jCheckBoxPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxPizzaMouseClicked(evt);
            }
        });
        jCheckBoxPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPizzaActionPerformed(evt);
            }
        });

        jCheckBoxFrenchFries.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxFrenchFries.setText("French Fries");
        jCheckBoxFrenchFries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxFrenchFriesMouseClicked(evt);
            }
        });
        jCheckBoxFrenchFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFrenchFriesActionPerformed(evt);
            }
        });

        jCheckBoxChickenChilli.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxChickenChilli.setText("Chicken Chilli");
        jCheckBoxChickenChilli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxChickenChilliMouseClicked(evt);
            }
        });

        jCheckBoxChickenWings.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxChickenWings.setText("Chicken Wings");
        jCheckBoxChickenWings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxChickenWingsMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Food Items");
        
        /**
         * RSyntaxTextArea textArea = new RSyntaxTextArea();
         * textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
         * RTextScrollPane sp = new RTextScrollPane(textArea);
         */
         
        
        jTextFieldMoMo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldMoMo.setText("0");

        jTextFieldBurger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBurger.setText("0");
        jTextFieldBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBurgerMouseClicked(evt);
            }
        });

        jTextFieldChowmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldChowmin.setText("0");

        jTextFieldPizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPizza.setText("0");
        jTextFieldPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPizzaActionPerformed(evt);
            }
        });

        jTextFieldFries.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFries.setText("0");

        jTextFieldChilli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldChilli.setText("0");

        jTextFieldWings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldWings.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxChowmin)
                            .addComponent(jCheckBoxBurger)
                            .addComponent(jCheckBoxFrenchFries)
                            .addComponent(jCheckBoxChickenWings)
                            .addComponent(jCheckBoxPizza)
                            .addComponent(jCheckBoxChickenChilli)
                            .addComponent(jCheckBoxChickenMoMo))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jTextFieldMoMo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldChowmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBurger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPizza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldChilli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldWings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMoMo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxChickenMoMo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldChowmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxChowmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBurger))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxPizza))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxFrenchFries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldChilli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxChickenChilli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxChickenWings))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldBurger, jTextFieldChilli, jTextFieldChowmin, jTextFieldFries, jTextFieldMoMo, jTextFieldPizza, jTextFieldWings});

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Cafe Items");

        jCheckBoxColdDrinks.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxColdDrinks.setText("Cold Drinks");
        jCheckBoxColdDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxColdDrinksMouseClicked(evt);
            }
        });
        jCheckBoxColdDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxColdDrinksActionPerformed(evt);
            }
        });

        jCheckBoxIcedCappuccino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxIcedCappuccino.setText("Iced Cappuccino");
        jCheckBoxIcedCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIcedCappuccinoMouseClicked(evt);
            }
        });
        jCheckBoxIcedCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIcedCappuccinoActionPerformed(evt);
            }
        });

        jCheckBoxBlackForest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxBlackForest.setText("Black Forest Cake");
        jCheckBoxBlackForest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBlackForestMouseClicked(evt);
            }
        });
        jCheckBoxBlackForest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBlackForestActionPerformed(evt);
            }
        });

        jCheckBoxBlueberry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxBlueberry.setText("Blueberry Cake");
        jCheckBoxBlueberry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxBlueberryMouseClicked(evt);
            }
        });

        jCheckBoxCreamedPie.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxCreamedPie.setText("Creamed Pie ");
        jCheckBoxCreamedPie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCreamedPieMouseClicked(evt);
            }
        });

        jCheckBoxWaterMelon.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxWaterMelon.setText("Watermelon Raspe");
        jCheckBoxWaterMelon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxWaterMelonMouseClicked(evt);
            }
        });
        jCheckBoxWaterMelon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxWaterMelonActionPerformed(evt);
            }
        });

        jCheckBoxDickyDan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxDickyDan.setText("Dicky Dan Pie");
        jCheckBoxDickyDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxDickyDanMouseClicked(evt);
            }
        });

        jTextFieldColdDrinks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldColdDrinks.setText("0");
        jTextFieldColdDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldColdDrinksActionPerformed(evt);
            }
        });

        jTextFieldIcedCappuccino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldIcedCappuccino.setText("0");

        jTextFieldBlackForest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBlackForest.setText("0");
        jTextFieldBlackForest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBlackForestMouseClicked(evt);
            }
        });

        jTextFieldBlueberry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldBlueberry.setText("0");
        jTextFieldBlueberry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBlueberryMouseClicked(evt);
            }
        });

        jTextFieldCreamedPie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCreamedPie.setText("0");
        jTextFieldCreamedPie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCreamedPieMouseClicked(evt);
            }
        });
        jTextFieldCreamedPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreamedPieActionPerformed(evt);
            }
        });

        jTextFieldWaterMelon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldWaterMelon.setText("0");
        jTextFieldWaterMelon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldWaterMelonMouseClicked(evt);
            }
        });

        jTextFieldDickyDan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDickyDan.setText("0");
        jTextFieldDickyDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDickyDanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCheckBoxIcedCappuccino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBoxColdDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jCheckBoxBlackForest))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIcedCappuccino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldColdDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldBlackForest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxBlueberry)
                                    .addComponent(jCheckBoxCreamedPie)
                                    .addComponent(jCheckBoxWaterMelon)
                                    .addComponent(jCheckBoxDickyDan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldDickyDan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBlueberry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextFieldCreamedPie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldWaterMelon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldBlackForest, jTextFieldBlueberry, jTextFieldColdDrinks, jTextFieldCreamedPie, jTextFieldDickyDan, jTextFieldIcedCappuccino, jTextFieldWaterMelon});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldColdDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jCheckBoxColdDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIcedCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxIcedCappuccino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBlackForest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBlackForest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBlueberry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBlueberry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreamedPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCreamedPie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWaterMelon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxWaterMelon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDickyDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxDickyDan))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldBlackForest, jTextFieldBlueberry, jTextFieldColdDrinks, jTextFieldCreamedPie, jTextFieldDickyDan, jTextFieldIcedCappuccino, jTextFieldWaterMelon});

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextAreaReceipt.setColumns(20);
        jTextAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Restaurant Management System");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\NTC\\Desktop\\images.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Food Tax:");

        jTextFieldFoodTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldFoodTax.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Sub Total:");

        jTextFieldSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSubTotal.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total:");

        jTextFieldTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTotal.setText("0");
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFoodTax, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldFoodTax, jTextFieldSubTotal, jTextFieldTotal});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldFoodTax, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldFoodTax, jTextFieldSubTotal, jTextFieldTotal});

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cost Of Food Item:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cost of Cafe Item:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Service Charge:");

        jTextFieldCostOfFoodItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCostOfFoodItem.setText("0");

        jTextFieldCostOfCafeItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCostOfCafeItem.setText("0");

        jTextFieldServiceCharge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldServiceCharge.setText("100");
        jTextFieldServiceCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServiceChargeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCostOfFoodItem)
                    .addComponent(jTextFieldCostOfCafeItem)
                    .addComponent(jTextFieldServiceCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCostOfFoodItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCostOfCafeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldServiceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldCostOfCafeItem, jTextFieldCostOfFoodItem, jTextFieldServiceCharge});

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButtonTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });

        jButtonReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReceipt.setText("Receipt");
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTotal)
                    .addComponent(jButtonReceipt)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonExit))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextAreaRandomId.setColumns(20);
        jTextAreaRandomId.setRows(5);
        jTextAreaRandomId.setPreferredSize(new java.awt.Dimension(164, 76));
        jScrollPane2.setViewportView(jTextAreaRandomId);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPizzaActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jCheckBoxChickenMoMoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxChickenMoMoActionPerformed

    }//GEN-LAST:event_jCheckBoxChickenMoMoActionPerformed

    private void jTextFieldColdDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldColdDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldColdDrinksActionPerformed

    private void jTextFieldServiceChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServiceChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServiceChargeActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jCheckBoxChickenMoMo.setSelected(false);
        jCheckBoxChowmin.setSelected(false);
        jCheckBoxBurger.setSelected(false);
        jCheckBoxChickenChilli.setSelected(false);
        jCheckBoxPizza.setSelected(false);
        jCheckBoxChickenWings.setSelected(false);
        jCheckBoxFrenchFries.setSelected(false);
        jCheckBoxColdDrinks.setSelected(false);
        jCheckBoxIcedCappuccino.setSelected(false);
        jCheckBoxBlackForest.setSelected(false);
        jCheckBoxBlueberry.setSelected(false);
        jCheckBoxCreamedPie.setSelected(false);
        jCheckBoxDickyDan.setSelected(false);
        jCheckBoxWaterMelon.setSelected(false);
        jTextFieldMoMo.setText("0");
        jTextFieldBlackForest.setText("0");
        jTextFieldBlueberry.setText("0");
        jTextFieldChowmin.setText("0");
        jTextFieldChilli.setText("0");
        jTextFieldBurger.setText("0");
        jTextFieldColdDrinks.setText("0");
        jTextFieldCostOfCafeItem.setText("0");
        jTextFieldCostOfFoodItem.setText("0");
        jTextFieldCreamedPie.setText("0");
        jTextFieldDickyDan.setText("0");
        jTextFieldFoodTax.setText("0");
        jTextFieldFries.setText("0");
        jTextFieldIcedCappuccino.setText("0");
        jTextFieldServiceCharge.setText("0");
        jTextFieldPizza.setText("0");
        jTextFieldSubTotal.setText("0");
        jTextFieldTotal.setText("0");
        jTextFieldWaterMelon.setText("0");
        jTextFieldWings.setText("0");
        jTextAreaReceipt.setText(null);
        jTextAreaRandomId.setText(null);

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        //for fooditems
        foodItem[0] = Double.parseDouble(jTextFieldMoMo.getText());
        foodItem[1] = Double.parseDouble(jTextFieldChowmin.getText());
        foodItem[2] = Double.parseDouble(jTextFieldBurger.getText());
        foodItem[3] = Double.parseDouble(jTextFieldPizza.getText());
        foodItem[4] = Double.parseDouble(jTextFieldFries.getText());
        foodItem[5] = Double.parseDouble(jTextFieldChilli.getText());
        foodItem[6] = Double.parseDouble(jTextFieldWings.getText());
        //for cafeitems
        cafeItem[0] = Double.parseDouble(jTextFieldColdDrinks.getText());
        cafeItem[1] = Double.parseDouble(jTextFieldIcedCappuccino.getText());
        cafeItem[2] = Double.parseDouble(jTextFieldBlackForest.getText());
        cafeItem[3] = Double.parseDouble(jTextFieldBlueberry.getText());
        cafeItem[4] = Double.parseDouble(jTextFieldCreamedPie.getText());
        cafeItem[5] = Double.parseDouble(jTextFieldWaterMelon.getText());
        cafeItem[6] = Double.parseDouble(jTextFieldDickyDan.getText());
        f[0]=Double.parseDouble(jTextFieldCostOfFoodItem.getText());
       f[1]=Double.parseDouble(jTextFieldCostOfCafeItem.getText());
       f[2]=Double.parseDouble(jTextFieldServiceCharge.getText());
       
       double cTotal=(f[0]+f[1]+f[2]);
       
       String iTaxTotal=String.format("Rs. %.2f", cTotal/100);
       
       double subTotal=(cTotal);
       String iSubTotal=String.format("Rs %.2f", subTotal );
       
       double allTotal=(cTotal);
       double serviceCharge=100.00;
       String iTotal=String.format("Rs %.2f", allTotal+(allTotal/100)+serviceCharge);
        //total
       //Calender--to add todays time and date
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        //(cal.getTime()))
        int random = 1326 + (int) (Math.random() * 4232);

        //append to the textarea to print the receipt
        jTextAreaReceipt.append("\t\tRestaurant Bill Receipt\t\t\n\t"+ "\n\t-------------------------------------------------------------------------------------------\t\n\t" + "Chicken MoMo:\t\t\t" + foodItem[0] + "\n\tChicken Chowmin:\t\t" + foodItem[1] + "\n\tChicken Burger:\t\t" + foodItem[2] + "\n\tChicken Pizza:\t\t\t" + foodItem[3] + "\n\tFrench Fries:\t\t\t" + foodItem[4] + "\n\tChicken Chilly:\t\t\t" + foodItem[5] + "\n\tChicken Wings:\t\t\t" + foodItem[6] + "\n\t-------------------------------------------------------------------------------------------\t\n" + "\tCold Drinks:\t\t\t" + cafeItem[0] + "\n\tIced Cappuccino:\t\t" + cafeItem[1] + "\n\tBlack Forest:\t\t\t" + cafeItem[2] + "\n\tBlueberry Cake:\t\t\t" + cafeItem[3] + "\n\tCreamed Pie:\t\t\t" + cafeItem[4] + "\n\tWatermelon Raspe:\t\t" + cafeItem[5] + "\n\tDicky Dan Pie:\t\t\t" + cafeItem[6] + "\n\t-----------------------------------------------------------------------------------------\t\n\t\t"+ "\n\tTax:\t\t\t" + iTaxTotal+ "\n\tSubTotal:\t\t\t" + iSubTotal + "\n\tTotal:\t\t\t" + iTotal + "\n\t-----------------------------------------------------------------------------------------\t\n\t\t" + cal.getTime() + "\n\t-----------------------------------------------------------------------------------------\t\n" + "\t\t--------Thank You---------");

        jTextAreaRandomId.append("Receipt ID\t" + random);


    }//GEN-LAST:event_jButtonReceiptActionPerformed

    private void jCheckBoxWaterMelonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxWaterMelonActionPerformed


    }//GEN-LAST:event_jCheckBoxWaterMelonActionPerformed

    private void jTextFieldCreamedPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreamedPieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreamedPieActionPerformed

    private void jCheckBoxChowminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxChowminActionPerformed

    }//GEN-LAST:event_jCheckBoxChowminActionPerformed

    private void jCheckBoxBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBurgerActionPerformed

    }//GEN-LAST:event_jCheckBoxBurgerActionPerformed

    private void jCheckBoxChickenMoMoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxChickenMoMoMouseClicked
        double cFood = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double tMomo = Double.parseDouble(jTextFieldMoMo.getText());
        double pMomo = 250;
        if (jCheckBoxChickenMoMo.isSelected()) {
            f[0] = (tMomo * pMomo) + cFood;
            String pValue = String.format("%.2f", f[0]);
            jTextFieldCostOfFoodItem.setText(pValue);

        }
    }//GEN-LAST:event_jCheckBoxChickenMoMoMouseClicked

    private void jCheckBoxChowminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxChowminMouseClicked
        double cFoodItem = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double nChowmin = Double.parseDouble(jTextFieldChowmin.getText());
        double price = 150.00;

        if (jCheckBoxChowmin.isSelected()) {
            f[1] = (price * nChowmin) + cFoodItem;
            String pChowmin = String.format("%.2f", f[1]);
            jTextFieldCostOfFoodItem.setText(pChowmin);

        }
    }//GEN-LAST:event_jCheckBoxChowminMouseClicked

    private void jCheckBoxBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBurgerMouseClicked
        double cFoodItem = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double nBurger = Double.parseDouble(jTextFieldBurger.getText());
        double price = 120.00;

        if (jCheckBoxBurger.isSelected()) {
            f[2] = (price * nBurger) + cFoodItem;
            String pBurger = String.format("%.2f", f[2]);
            jTextFieldCostOfFoodItem.setText(pBurger);

        }
    }//GEN-LAST:event_jCheckBoxBurgerMouseClicked

    private void jCheckBoxPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxPizzaMouseClicked
        double cFoodItem = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double nPizza = Double.parseDouble(jTextFieldPizza.getText());
        double price = 230.00;

        if (jCheckBoxPizza.isSelected()) {
            f[3] = (price * nPizza) + cFoodItem;
            String pPizza = String.format("%.2f", f[3]);
            jTextFieldCostOfFoodItem.setText(pPizza);

        }
    }//GEN-LAST:event_jCheckBoxPizzaMouseClicked


    private void jCheckBoxPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPizzaActionPerformed

    private void jCheckBoxFrenchFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFrenchFriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxFrenchFriesActionPerformed

    private void jCheckBoxFrenchFriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxFrenchFriesMouseClicked
        double cFoodItem = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double nFrenchFries = Double.parseDouble(jTextFieldFries.getText());
        double price = 100.00;

        if (jCheckBoxFrenchFries.isSelected()) {
            f[4] = (price * nFrenchFries) + cFoodItem;
            String pFries = String.format("%.2f", f[4]);
            jTextFieldCostOfFoodItem.setText(pFries);
        }
    }//GEN-LAST:event_jCheckBoxFrenchFriesMouseClicked

    private void jCheckBoxChickenChilliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxChickenChilliMouseClicked
        double cFoodItem = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double nChickenChilli = Double.parseDouble(jTextFieldChilli.getText());
        double price = 270.00;

        if (jCheckBoxChickenChilli.isSelected()) {
            f[5] = (price * nChickenChilli) + cFoodItem;
            String pChilli = String.format("%.2f", f[5]);
            jTextFieldCostOfFoodItem.setText(pChilli);
        }
    }//GEN-LAST:event_jCheckBoxChickenChilliMouseClicked

    private void jCheckBoxChickenWingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxChickenWingsMouseClicked
        double cFoodItem = Double.parseDouble(jTextFieldCostOfFoodItem.getText());
        double nChickenWings = Double.parseDouble(jTextFieldWings.getText());
        double price = 350.00;

        if (jCheckBoxChickenWings.isSelected()) {
            f[6] = (price * nChickenWings) + cFoodItem;
            String pWings = String.format("%.2f", f[6]);
            jTextFieldCostOfFoodItem.setText(pWings);
        }
    }//GEN-LAST:event_jCheckBoxChickenWingsMouseClicked

    private void jCheckBoxColdDrinksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxColdDrinksMouseClicked
        double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nColdDrinks = Double.parseDouble(jTextFieldColdDrinks.getText());
        double price = 40.00;

        if (jCheckBoxColdDrinks.isSelected()) {
            c[0] = (price * nColdDrinks) + cCafeItem;
            String pColdDrinks = String.format("%.2f", c[0]);
            jTextFieldCostOfCafeItem.setText(pColdDrinks);

        }
    }//GEN-LAST:event_jCheckBoxColdDrinksMouseClicked

    private void jCheckBoxColdDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxColdDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxColdDrinksActionPerformed

    private void jCheckBoxIcedCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIcedCappuccinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxIcedCappuccinoActionPerformed

    private void jCheckBoxIcedCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIcedCappuccinoMouseClicked
        double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nIcedCappuccino = Double.parseDouble(jTextFieldIcedCappuccino.getText());
        double price = 230.00;

        if (jCheckBoxIcedCappuccino.isSelected()) {
            c[1] = (price * nIcedCappuccino) + cCafeItem;
            String pIcedCappuccino = String.format("%.2f", c[1]);
            jTextFieldCostOfCafeItem.setText(pIcedCappuccino);

        }
    }//GEN-LAST:event_jCheckBoxIcedCappuccinoMouseClicked

    private void jCheckBoxBlackForestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBlackForestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxBlackForestActionPerformed

    private void jTextFieldBlackForestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBlackForestMouseClicked

    }//GEN-LAST:event_jTextFieldBlackForestMouseClicked

    private void jTextFieldBlueberryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBlueberryMouseClicked
     
    }//GEN-LAST:event_jTextFieldBlueberryMouseClicked

    private void jTextFieldCreamedPieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCreamedPieMouseClicked
     
    }//GEN-LAST:event_jTextFieldCreamedPieMouseClicked

    private void jTextFieldWaterMelonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldWaterMelonMouseClicked

    }//GEN-LAST:event_jTextFieldWaterMelonMouseClicked

    private void jTextFieldDickyDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDickyDanMouseClicked

    }//GEN-LAST:event_jTextFieldDickyDanMouseClicked

    private void jCheckBoxWaterMelonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxWaterMelonMouseClicked
        double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nWaterMelon = Double.parseDouble(jTextFieldWaterMelon.getText());
        double price = 210.00;

        if (jCheckBoxWaterMelon.isSelected()) {
            c[5] = (price * nWaterMelon) + cCafeItem;
            String pWaterMelon = String.format("%.2f", c[5]);
            jTextFieldCostOfCafeItem.setText(pWaterMelon);

        }
    }//GEN-LAST:event_jCheckBoxWaterMelonMouseClicked

    private void jCheckBoxDickyDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxDickyDanMouseClicked
        double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nDickyDan = Double.parseDouble(jTextFieldDickyDan.getText());
        double price = 120.00;

        if (jCheckBoxDickyDan.isSelected()) {
            c[6] = (price * nDickyDan) + cCafeItem;
            String pDickyDan = String.format("%.2f", c[6]);
            jTextFieldCostOfCafeItem.setText(pDickyDan);

        }
    }//GEN-LAST:event_jCheckBoxDickyDanMouseClicked

    private void jTextFieldBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBurgerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBurgerMouseClicked

    private void jCheckBoxBlackForestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBlackForestMouseClicked
        double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nBlackForest = Double.parseDouble(jTextFieldBlackForest.getText());
        double price = 120.00;

        if (jCheckBoxBlackForest.isSelected()) {
            c[2] = (price * nBlackForest) + cCafeItem;
            String pBlackForest = String.format("%.2f", c[2]);
            jTextFieldCostOfCafeItem.setText(pBlackForest);

        }
    }//GEN-LAST:event_jCheckBoxBlackForestMouseClicked

    private void jCheckBoxBlueberryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxBlueberryMouseClicked
        double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nBlueberry = Double.parseDouble(jTextFieldBlueberry.getText());
        double price = 170.00;

        if (jCheckBoxBlueberry.isSelected()) {
            c[3] = (price * nBlueberry) + cCafeItem;
            String pBlueberry = String.format("%.2f", c[3]);
            jTextFieldCostOfCafeItem.setText(pBlueberry);

        }
    }//GEN-LAST:event_jCheckBoxBlueberryMouseClicked

    private void jCheckBoxCreamedPieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCreamedPieMouseClicked
          double cCafeItem = Double.parseDouble(jTextFieldCostOfCafeItem.getText());
        double nCreamedPie = Double.parseDouble(jTextFieldCreamedPie.getText());
        double price = 230.00;

        if (jCheckBoxCreamedPie.isSelected()) {
            c[4] = (price * nCreamedPie) + cCafeItem;
            String pCreamedPie = String.format("%.2f", c[4]);
            jTextFieldCostOfCafeItem.setText(pCreamedPie);

        }
    }//GEN-LAST:event_jCheckBoxCreamedPieMouseClicked

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
       f[0]=Double.parseDouble(jTextFieldCostOfFoodItem.getText());
       f[1]=Double.parseDouble(jTextFieldCostOfCafeItem.getText());
       f[2]=Double.parseDouble(jTextFieldServiceCharge.getText());
       
       double cTotal=(f[0]+f[1]+f[2]);
       
       String iTaxTotal=String.format("Rs. %.2f", cTotal/100);
       jTextFieldFoodTax.setText(iTaxTotal);
       
       double subTotal=(cTotal);
       String iSubTotal=String.format("Rs %.2f", subTotal );
       jTextFieldSubTotal.setText(iSubTotal);
       
       double allTotal=(cTotal);
       double serviceCharge=100.00;
       String iTotal=String.format("Rs %.2f", allTotal+(allTotal/100)+serviceCharge);
       jTextFieldTotal.setText(iTotal);
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RestaurantManagementSystem().setVisible(true);
        });
    }

    